image: androidsdk/android-31

stages:
  - test
  - publish

test:
  stage: test
  script:
    # lint
    - ./gradlew -Pci --console=plain lintDebug -PbuildDir=lint
    - ./gradlew -Pci --console=plain ktlintCheck
    # test
    - ./gradlew -Pci --console=plain clean # to make sure that rest results are reported
    - ./gradlew -Pci --console=plain test

publish:
  stage: publish
  only:
    - tags
  script:
    - export RELEASE_VERSION=$CI_COMMIT_TAG
    - ./gradlew -Pci --console=plain build
    - ./gradlew -Pci --console=plain publish
