image: androidsdk/android-31

stages:
  - test
  - publish

test:
  stage: test
  script:
    - ./gradlew -Pci --console=plain :openread:lintDebug -PbuildDir=lint
    - ./gradlew -Pci --console=plain :openread:ktlintCheck
    - ./gradlew -Pci --console=plain :openread:test

publish:
  stage: publish
  only:
    - tags
  script:
    - export RELEASE_VERSION=$CI_COMMIT_TAG
    - ./gradlew -Pci --console=plain :openread:build
    - ./gradlew -Pci --console=plain :openread:publish
